#!/usr/bin/env/python
import usb.core
import usb.util
import codecs
import sys

#EP_IN = 0x81
#EP_OUT = 0x01

#def connect_to_printer():
dev = usb.core.find(idVendor=0xa5f, idProduct=0x0f3)

    #was the device found
if dev is None:
    raise ValueError('Device not found')
if dev.is_kernel_driver_active(0):
    print("Detaching kernel driver")
    reattach = True
    dev.detach_kernel_driver(0)

# show config / interface / endpoints:
for config in dev:
    sys.stdout.write('Config ' + str(config.bConfigurationValue) + '\n')
    for interface in config:
        sys.stdout.write('\t' + \
            'Interface ' + str(interface.bInterfaceNumber) + \
                         ',' + \
                         str(interface.bAlternateSetting) + \
                         '\n')
        for endpoint in interface:
            sys.stdout.write('\t\t' + \
                             'Endpoint ' + str(endpoint.bEndpointAddress) + \
                             '\n')
dev.set_configuration()

    # get an endpoint instance
cfg = dev.get_active_configuration()
intf= cfg[(0,0)]

ep = usb.util.find_descriptor(
    intf,
    # match the first OUT endpoint
    custom_match = \
    lambda e: \
        usb.util.endpoint_direction(e.bEndpointAddress) == \
        usb.util.ENDPOINT_OUT)

    # Write to the Printer

#empty = "\0x00"
#dev.write(1, empty)
#msg2 = bytearray('"! U1 getvar "comm.baud"\r\n', 'utf-8')
msg2 = '^XA^FO150,100^**BY1**^BC,100,Y,N,N^FD00V11636000032562050^FS^XZ'
print(msg2)
#msg = codecs.encode(msg.encode("ascii"), "hex")
dev.write(1, msg2)

ret = dev.read(1, ep.wMaxPacketSize,timeout=1000)
print(codecs.encode(ret, "hex").decode('utf-8'))

# This is needed to release interface, otherwise attach_kernel_driver fails
# due to "Resource busy"
usb.util.dispose_resources(dev)

# It may raise USBError if there's e.g. no kernel driver loaded at all
#if reattach:
#    dev.attach_kernel_driver(0)
